### ISSUE TITLE
Pretrained Models

### ISSUE THREAD

**Issue by ldkong1205** [lordzth666/WACV23_PIDS-Joint-Point-Interaction-Dimension-Search-for-3D-Point-Cloud#1]
Hi @lordzth666, thanks for open-sourcing your work!

I would like to know if it is applicable for you to release the checkpoints / trained model weights. Thanks for your help!

**Comment by lordzth666** [comment]
Hi, @ldkong1205,

Thank you for your interest on our work. You will see the checkpoints uploaded within 12 hours.

--Tunhou

**Comment by lordzth666** [comment]
The checkpoints are already released in README. Closing this issue now.

**Comment by ldkong1205** [comment]
Appreciate your prompt help!
